import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import SupabaseProvider from '@/providers/SupabaseProvider'
import UserProvider from '@/providers/UserProvider'
import ModalProvider from '@/providers/ModalProvider'
import ToasterProvider from '@/providers/ToasterProvider'
import getSongsByUserId from '@/actions/getSongsByUserId.ts'
import Player from '@/components/Player'
import getActiveProductsWithPrices from '@/actions/getActiveProductsWithPrices'
import { BiCopyright } from 'react-icons/bi'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BeatBox - Made by Akash ©' ,
  description: 'Enjoy all your favourite and trending music only on BeatBox version@1.0.0',
}

export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const userSongs = await getSongsByUserId();
  const products = await getActiveProductsWithPrices();


  return (
    <html lang="en">
      <head>
        {/* Meta Tags Dynamically generated by metaseo.itsvg.in */}
        <meta name ="title" content ="BeatBox Music"/>
        <meta name ="description" content ="It is a songs app created using Nextjs13, React, TypeScript and Tailwind CSS.   "/>
        <meta name ="copyright" content ="Akash Shridharan"/>
        <meta name ="keywords" content ="music app beatbox spotify songs trending latest songs premium feature playlist liked songs bollywood and south songs honey singh"/>
        <meta property ="og:type" content ="website"/>
        <meta property ="og:url" content ="https://beatboxmusic.vercel.app/"/>
        <meta property ="og:title" content ="BeatBox Music"/>
        <meta property ="og:description" content ="It is a songs app created using Nextjs13, React, TypeScript and Tailwind CSS.   "/>
        <meta property ="og:image" content ="http://res.cloudinary.com/dpu5ywrox/image/upload/v1692553666/twesw2cinmdp0ct6i2pj.png"/>
        <meta property ="twitter:card" content ="summary_large_image"/>
        <meta property ="twitter:url" content ="https://beatboxmusic.vercel.app/"/>
        <meta property ="twitter:title" content ="BeatBox Music"/>
        <meta property ="twitter:description" content ="It is a songs app created using Nextjs13, React, TypeScript and Tailwind CSS.   "/>
        <meta property ="twitter:image" content ="http://res.cloudinary.com/dpu5ywrox/image/upload/v1692553666/twesw2cinmdp0ct6i2pj.png"/>

      </head>
      <body className={font.className}>
        <ToasterProvider/>
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider products={products} />
            <Sidebar songs={userSongs}>
              {children}
            </Sidebar>
            <Player />
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
